name: norviz
favicon: null
layout_spectrum: 0.5062445527873933
typography_spectrum: 0.5228602241259068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
